# Generated by Django 5.1.3 on 2025-06-01 10:18

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.get_path_upload_images),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('new', 'new')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='8 999 999 99 99', max_length=17),
        ),
    ]
