# Generated by Django 5.1.3 on 2025-06-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_coordinates_latitude_and_more'),
        ('project', '0004_alter_images_data_alter_pereval_status'),
    ]

    operations = [
    ]
